spring:
  datasource:
    username: sharding
    url: jdbc:mysql://127.0.0.1:3309/sharding_db?serverTimezone=UTC&useSSL=false
    password: sharding
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml



